// Copyright (c) Sui Potatoes
// SPDX-License-Identifier: MIT

// prettier-ignore
module name_gen::last_name;

use std::string::String;

const BUCKET_0: vector<vector<u8>> = vector[b"Charlesworth", b"Ball", b"Smith", b"Johnson", b"Sanderson", b"White", b"Smith", b"Savage", b"Waite", b"Noble"];
const BUCKET_1: vector<vector<u8>> = vector[b"Mae", b"Abbott", b"Abney", b"Abnett", b"Acevedo", b"Acosta", b"Adams", b"Adkins", b"Adrichem", b"Aguilar"];
const BUCKET_2: vector<vector<u8>> = vector[b"Aguirre", b"Albert", b"Alexander", b"Alford", b"Allen", b"Allison", b"Alston", b"Alvarado", b"Alvarez", b"Anderson"];
const BUCKET_3: vector<vector<u8>> = vector[b"Andrews", b"Anthony", b"Appleton", b"Appleby", b"Armstrong", b"Archibald", b"Arnold", b"Ashley", b"Aston", b"Ashworth"];
const BUCKET_4: vector<vector<u8>> = vector[b"Atkins", b"Atkinson", b"Austin", b"Avery", b"Avila", b"Ayala", b"Ayers", b"Ayton", b"Bailey", b"Baird"];
const BUCKET_5: vector<vector<u8>> = vector[b"Baker", b"Baldwin", b"Ball", b"Ballard", b"Banks", b"Barber", b"Barker", b"Barlow", b"Barnes", b"Barnett"];
const BUCKET_6: vector<vector<u8>> = vector[b"Barr", b"Barrera", b"Barrett", b"Barron", b"Barry", b"Bartlett", b"Barton", b"Bass", b"Bates", b"Battle"];
const BUCKET_7: vector<vector<u8>> = vector[b"Bauer", b"Baxter", b"Bagshaw", b"Backshawl", b"Beach", b"Bean", b"Beard", b"Beasley", b"Beck", b"Becker"];
const BUCKET_8: vector<vector<u8>> = vector[b"Bell", b"Bender", b"Benjamin", b"Bennett", b"Benson", b"Bentley", b"Benton", b"Berg", b"Berger", b"Bernard"];
const BUCKET_9: vector<vector<u8>> = vector[b"Berry", b"Best", b"Bird", b"Bishop", b"Black", b"Blackburn", b"Blackwell", b"Blair", b"Blake", b"Blanchard"];
const BUCKET_10: vector<vector<u8>> = vector[b"Blankenship", b"Blevins", b"Bolton", b"Bond", b"Bonner", b"Booker", b"Boone", b"Booth", b"Bowen", b"Bowers"];
const BUCKET_11: vector<vector<u8>> = vector[b"Bowman", b"Boyd", b"Boyer", b"Boyle", b"Bradford", b"Bradley", b"Bradshaw", b"Brady", b"Branch", b"Bray"];
const BUCKET_12: vector<vector<u8>> = vector[b"Brennan", b"Brewer", b"Bridges", b"Briggs", b"Bright", b"Britt", b"Brock", b"Brooks", b"Brown", b"Browning"];
const BUCKET_13: vector<vector<u8>> = vector[b"Bruce", b"Bryan", b"Bryant", b"Buchanan", b"Buck", b"Buckley", b"Buckner", b"Budd", b"Bullock", b"Burch"];
const BUCKET_14: vector<vector<u8>> = vector[b"Burgess", b"Burke", b"Burks", b"Burnett", b"Burns", b"Burris", b"Burt", b"Burton", b"Busto", b"Bush"];
const BUCKET_15: vector<vector<u8>> = vector[b"Butler", b"Byers", b"Byrd", b"Cabrera", b"Cain", b"Calderon", b"Caldwell", b"Calhoun", b"Callahan", b"Camacho"];
const BUCKET_16: vector<vector<u8>> = vector[b"Cameron", b"Campbell", b"Campos", b"Cannon", b"Cantrell", b"Cantu", b"Cardenas", b"Carey", b"Carlson", b"Carlyle"];
const BUCKET_17: vector<vector<u8>> = vector[b"Carlisle", b"Carney", b"Carpenter", b"Carr", b"Caron", b"Carrillo", b"Carroll", b"Carson", b"Carter", b"Carver"];
const BUCKET_18: vector<vector<u8>> = vector[b"Case", b"Casey", b"Cason", b"Cash", b"Castaneda", b"Castillo", b"Castro", b"Cervantes", b"Chambers", b"Chan"];
const BUCKET_19: vector<vector<u8>> = vector[b"Chandler", b"Chaney", b"Chang", b"Chapman", b"Charles", b"Chase", b"Chatman", b"Chavez", b"Chen", b"Cherry"];
const BUCKET_20: vector<vector<u8>> = vector[b"Chevrolet", b"Christensen", b"Christian", b"Church", b"Clark", b"Clarke", b"Clay", b"Clayton", b"Clements", b"Clemons"];
const BUCKET_21: vector<vector<u8>> = vector[b"Cleveland", b"Cline", b"Cobb", b"Cochran", b"Coffey", b"Cohen", b"Cole", b"Coleman", b"Collier", b"Collins"];
const BUCKET_22: vector<vector<u8>> = vector[b"Colon", b"Combs", b"Compton", b"Conley", b"Conner", b"Conrad", b"Contreras", b"Conway", b"Cook", b"Cooke"];
const BUCKET_23: vector<vector<u8>> = vector[b"Cooley", b"Cooper", b"Copeland", b"Cortez", b"Cote", b"Cotton", b"Couture", b"Cox", b"Craft", b"Craig"];
const BUCKET_24: vector<vector<u8>> = vector[b"Crane", b"Crawford", b"Crosby", b"Cross", b"Cruz", b"Cummings", b"Cunningham", b"Curry", b"Curtis", b"Dale"];
const BUCKET_25: vector<vector<u8>> = vector[b"Dalton", b"Daniel", b"Daniels", b"Daugherty", b"Davenport", b"David", b"Davidson", b"Davis", b"Dawson", b"Day"];
const BUCKET_26: vector<vector<u8>> = vector[b"Dean", b"Decker", b"Dejesus", b"Delacruz", b"Delaney", b"Deleon", b"Delgado", b"Dennis", b"Diaz", b"Dickerson"];
const BUCKET_27: vector<vector<u8>> = vector[b"Dickson", b"Dillard", b"Dillon", b"Dixon", b"Dodson", b"Dominguez", b"Donaldson", b"Donovan", b"Dorsey", b"Dotson"];
const BUCKET_28: vector<vector<u8>> = vector[b"Douglas", b"Downs", b"Doyle", b"Drake", b"Dudley", b"Duffy", b"Duke", b"Duncan", b"Dunlap", b"Dunn"];
const BUCKET_29: vector<vector<u8>> = vector[b"Duran", b"Durham", b"Dyer", b"Eaton", b"Edwards", b"Elliott", b"Ellis", b"Ellison", b"Ellwood", b"Emerson"];
const BUCKET_30: vector<vector<u8>> = vector[b"England", b"English", b"Erickson", b"Espinoza", b"Estes", b"Estrada", b"Evans", b"Everett", b"Ewing", b"Farley"];
const BUCKET_31: vector<vector<u8>> = vector[b"Farmer", b"Farrell", b"Faulkner", b"Ferguson", b"Fernandez", b"Ferrell", b"Fields", b"Figueroa", b"Finch", b"Finley"];
const BUCKET_32: vector<vector<u8>> = vector[b"Fischer", b"Fisher", b"Fitzgerald", b"Fitzpatrick", b"Fleming", b"Fletcher", b"Flores", b"Flowers", b"Floyd", b"Flynn"];
const BUCKET_33: vector<vector<u8>> = vector[b"Foley", b"Forbes", b"Ford", b"Foreman", b"Foster", b"Fowler", b"Fox", b"Francis", b"Franco", b"Frank"];
const BUCKET_34: vector<vector<u8>> = vector[b"Franklin", b"Franks", b"Frazier", b"Frederick", b"Freeman", b"French", b"Frost", b"Fry", b"Frye", b"Fuentes"];
const BUCKET_35: vector<vector<u8>> = vector[b"Fuller", b"Fulton", b"Gaines", b"Gallagher", b"Gallegos", b"Galloway", b"Gamble", b"Garcia", b"Gardner", b"Garner"];
const BUCKET_36: vector<vector<u8>> = vector[b"Garrett", b"Garrison", b"Garza", b"Gates", b"Gay", b"Gentry", b"George", b"Gibbs", b"Gibson", b"Gilbert"];
const BUCKET_37: vector<vector<u8>> = vector[b"Giles", b"Gill", b"Gillespie", b"Gilliam", b"Gilmore", b"Glass", b"Glenn", b"Glover", b"Goff", b"Golden"];
const BUCKET_38: vector<vector<u8>> = vector[b"Gomez", b"Gonzales", b"Gonzalez", b"Good", b"Goodman", b"Goodwin", b"Gordon", b"Gould", b"Graham", b"Grant"];
const BUCKET_39: vector<vector<u8>> = vector[b"Graves", b"Gray", b"Green", b"Greene", b"Greer", b"Gregory", b"Griffin", b"Griffith", b"Grimes", b"Gross"];
const BUCKET_40: vector<vector<u8>> = vector[b"Guerra", b"Guerrero", b"Guthrie", b"Gutierrez", b"Guy", b"Guzman", b"Hahn", b"Hale", b"Haley", b"Hall"];
const BUCKET_41: vector<vector<u8>> = vector[b"Hamilton", b"Hammond", b"Hampton", b"Hancock", b"Haney", b"Hansen", b"Hanson", b"Hardin", b"Harding", b"Hardy"];
const BUCKET_42: vector<vector<u8>> = vector[b"Harmon", b"Harper", b"Harrell", b"Harrington", b"Harris", b"Harrison", b"Hart", b"Hartman", b"Harvey", b"Hatfield"];
const BUCKET_43: vector<vector<u8>> = vector[b"Hawkins", b"Hayden", b"Hayes", b"Haynes", b"Hays", b"Head", b"Heath", b"Hebert", b"Henderson", b"Hendricks"];
const BUCKET_44: vector<vector<u8>> = vector[b"Hendrix", b"Henry", b"Hensley", b"Henson", b"Herman", b"Hernandez", b"Herrera", b"Herring", b"Hess", b"Hester"];
const BUCKET_45: vector<vector<u8>> = vector[b"Hewitt", b"Hickman", b"Hicks", b"Higgins", b"Hill", b"Hines", b"Hinton", b"Hobbs", b"Hodge", b"Hodges"];
const BUCKET_46: vector<vector<u8>> = vector[b"Hoffman", b"Hogan", b"Holcomb", b"Holden", b"Holder", b"Holland", b"Holloway", b"Holman", b"Holmes", b"Holt"];
const BUCKET_47: vector<vector<u8>> = vector[b"Hood", b"Hooper", b"Hoover", b"Hopkins", b"Hopper", b"Horn", b"Horne", b"Horton", b"House", b"Houston"];
const BUCKET_48: vector<vector<u8>> = vector[b"Howard", b"Howe", b"Howell", b"Hubbard", b"Huber", b"Hudson", b"Huff", b"Huffman", b"Hughes", b"Hull"];
const BUCKET_49: vector<vector<u8>> = vector[b"Humphrey", b"Hunt", b"Hunter", b"Hurley", b"Hurst", b"Hutchinson", b"Hyde", b"Ingram", b"Irwin", b"Jackson"];
const BUCKET_50: vector<vector<u8>> = vector[b"Jacobs", b"Jacobson", b"James", b"Jarvis", b"Jefferson", b"Jenkins", b"Jennings", b"Jensen", b"Jimenez", b"Johns"];
const BUCKET_51: vector<vector<u8>> = vector[b"Johnson", b"Johnston", b"Jones", b"Jordan", b"Joseph", b"Joyce", b"Joyner", b"Juarez", b"Justice", b"Kane"];
const BUCKET_52: vector<vector<u8>> = vector[b"Kaufman", b"Keith", b"Keller", b"Kelley", b"Kelly", b"Kemp", b"Kennedy", b"Kent", b"Kerr", b"Key"];
const BUCKET_53: vector<vector<u8>> = vector[b"Kidd", b"Kim", b"King", b"Kinney", b"Kirby", b"Kirk", b"Kirkland", b"Klein", b"Kline", b"Knapp"];
const BUCKET_54: vector<vector<u8>> = vector[b"Knight", b"Knowles", b"Knox", b"Koch", b"Kramer", b"Lamb", b"Lambert", b"Lancaster", b"Landry", b"Lane"];
const BUCKET_55: vector<vector<u8>> = vector[b"Lang", b"Langley", b"Lara", b"Larsen", b"Larson", b"Lawrence", b"Lawson", b"Le", b"Leach", b"Leblanc"];
const BUCKET_56: vector<vector<u8>> = vector[b"Lee", b"Leon", b"Leonard", b"Lester", b"Levine", b"Levy", b"Lewis", b"Lindsay", b"Lindsey", b"Little"];
const BUCKET_57: vector<vector<u8>> = vector[b"Livingston", b"Lloyd", b"Logan", b"Long", b"Lopez", b"Lott", b"Love", b"Lowe", b"Lofthouse", b"Lowery"];
const BUCKET_58: vector<vector<u8>> = vector[b"Lucas", b"Luna", b"Lynch", b"Lynn", b"Lyons", b"Macdonald", b"Macias", b"Mack", b"Madden", b"Maddox"];
const BUCKET_59: vector<vector<u8>> = vector[b"Maldonado", b"Malone", b"Mann", b"Manning", b"Marks", b"Marquez", b"Marsh", b"Marshall", b"Martin", b"Martinez"];
const BUCKET_60: vector<vector<u8>> = vector[b"Mason", b"Massey", b"Mathews", b"Mathis", b"Matthews", b"Maxwell", b"May", b"Mayer", b"Maynard", b"Mayo"];
const BUCKET_61: vector<vector<u8>> = vector[b"Mays", b"Magdalen", b"Magdalin", b"Mcbride", b"Mccall", b"Mccarthy", b"Mccarty", b"Mcclain", b"Mcclure", b"Mcconnell"];
const BUCKET_62: vector<vector<u8>> = vector[b"Mccormick", b"Mccoy", b"Mccray", b"Mccullough", b"Mcdaniel", b"Mcdonald", b"Mcdowell", b"Mcfadden", b"Mcfarland", b"Mcgee"];
const BUCKET_63: vector<vector<u8>> = vector[b"Mcgowan", b"Mcguire", b"Mcintosh", b"Mcintyre", b"Mckay", b"Mckee", b"Mckenzie", b"Mckinney", b"Mcknight", b"Mclaughlin"];
const BUCKET_64: vector<vector<u8>> = vector[b"Mclean", b"Mcleod", b"Mcmahon", b"Mcmillan", b"Mcneil", b"Mcpherson", b"Meadows", b"Medina", b"Mejia", b"Melendez"];
const BUCKET_65: vector<vector<u8>> = vector[b"Melton", b"Mendez", b"Mendoza", b"Mercado", b"Mercer", b"Merrill", b"Merritt", b"Meyer", b"Meyers", b"Michael"];
const BUCKET_66: vector<vector<u8>> = vector[b"Middleton", b"Miles", b"Miller", b"Mills", b"Miranda", b"Mitchell", b"Molina", b"Monroe", b"Montgomery", b"Montoya"];
const BUCKET_67: vector<vector<u8>> = vector[b"Moody", b"Moon", b"Mooney", b"Moore", b"Morales", b"Moran", b"Moreno", b"Morgan", b"Morin", b"Morris"];
const BUCKET_68: vector<vector<u8>> = vector[b"Morrison", b"Morrow", b"Morse", b"Morton", b"Moses", b"Mosley", b"Moss", b"Mueller", b"Mullen", b"Mullins"];
const BUCKET_69: vector<vector<u8>> = vector[b"Munoz", b"Murphy", b"Murray", b"Myers", b"Nash", b"Navarro", b"Naylor", b"Neal", b"Nelson", b"Newman"];
const BUCKET_70: vector<vector<u8>> = vector[b"Newton", b"Nevin", b"Nguyen", b"Nichols", b"Nicholson", b"Nielsen", b"Nieves", b"Nixon", b"Noble", b"Noel"];
const BUCKET_71: vector<vector<u8>> = vector[b"Nolan", b"Norman", b"Norris", b"Norton", b"Nunez", b"Obrien", b"Ochoa", b"Oconnor", b"Odom", b"Odonnell"];
const BUCKET_72: vector<vector<u8>> = vector[b"Oliver", b"Olsen", b"Olson", b"Oluo", b"Oneal", b"Oneil", b"Oneill", b"Orr", b"Ortega", b"Ortiz"];
const BUCKET_73: vector<vector<u8>> = vector[b"Osborn", b"Osborne", b"Owen", b"Owens", b"Pace", b"Pacheco", b"Padilla", b"Page", b"Palmer", b"Park"];
const BUCKET_74: vector<vector<u8>> = vector[b"Parker", b"Parks", b"Parkinson", b"Parrish", b"Parsons", b"Pate", b"Patel", b"Patrick", b"Patterson", b"Patton"];
const BUCKET_75: vector<vector<u8>> = vector[b"Paul", b"Payne", b"Pearson", b"Peck", b"Pena", b"Pennington", b"Perez", b"Perkins", b"Perry", b"Peters"];
const BUCKET_76: vector<vector<u8>> = vector[b"Petersen", b"Peterson", b"Petty", b"Phelps", b"Phillips", b"Pickett", b"Pierce", b"Pittman", b"Pitts", b"Pollard"];
const BUCKET_77: vector<vector<u8>> = vector[b"Poole", b"Pope", b"Porter", b"Potter", b"Potts", b"Powell", b"Powers", b"Pratt", b"Preston", b"Price"];
const BUCKET_78: vector<vector<u8>> = vector[b"Prince", b"Pruitt", b"Puckett", b"Pugh", b"Quinn", b"Ramirez", b"Ramos", b"Ramsey", b"Randall", b"Randolph"];
const BUCKET_79: vector<vector<u8>> = vector[b"Rasmussen", b"Ratliff", b"Ratly", b"Ratkinson", b"Ray", b"Raymond", b"Reed", b"Reese", b"Reeves", b"Reid"];
const BUCKET_80: vector<vector<u8>> = vector[b"Reilly", b"Reyes", b"Reynolds", b"Rhodes", b"Rice", b"Rich", b"Richard", b"Richards", b"Richardson", b"Richmond"];
const BUCKET_81: vector<vector<u8>> = vector[b"Riddle", b"Riggs", b"Riley", b"Rios", b"Rivas", b"Rivera", b"Rivers", b"Roach", b"Robbins", b"Roberson"];
const BUCKET_82: vector<vector<u8>> = vector[b"Roberts", b"Robertson", b"Robinson", b"Robles", b"Rocha", b"Rodgers", b"Rodriguez", b"Rodriquez", b"Rogers", b"Rojas"];
const BUCKET_83: vector<vector<u8>> = vector[b"Rollins", b"Roman", b"Romero", b"Rosa", b"Rosales", b"Rosario", b"Rose", b"Ross", b"Roth", b"Rowe"];
const BUCKET_84: vector<vector<u8>> = vector[b"Rowland", b"Roy", b"Ruiz", b"Rush", b"Russell", b"Russo", b"Rutledge", b"Ryan", b"Salas", b"Salazar"];
const BUCKET_85: vector<vector<u8>> = vector[b"Salinas", b"Sampson", b"Sanchez", b"Sanders", b"Sandoval", b"Sanford", b"Santana", b"Santiago", b"Santos", b"Sargent"];
const BUCKET_86: vector<vector<u8>> = vector[b"Saunders", b"Savage", b"Sawyer", b"Schmidt", b"Schneider", b"Schroeder", b"Schultz", b"Schwartz", b"Scott", b"Sears"];
const BUCKET_87: vector<vector<u8>> = vector[b"Sellers", b"Serrano", b"Sethin", b"Sexton", b"Shaffer", b"Shannon", b"Sharp", b"Sharpe", b"Shaw", b"Shelton"];
const BUCKET_88: vector<vector<u8>> = vector[b"Shepard", b"Shepherd", b"Sheppard", b"Sherman", b"Shields", b"Short", b"Silva", b"Simmons", b"Simon", b"Simpson"];
const BUCKET_89: vector<vector<u8>> = vector[b"Sims", b"Singleton", b"Skinner", b"Slater", b"Sloan", b"Small", b"Smith", b"Snider", b"Snow", b"Snyder"];
const BUCKET_90: vector<vector<u8>> = vector[b"Solis", b"Solomon", b"Sosa", b"Soto", b"Sparks", b"Spears", b"Spence", b"Spencer", b"Stafford", b"Stanley"];
const BUCKET_91: vector<vector<u8>> = vector[b"Stanton", b"Standish", b"Stark", b"Steele", b"Stein", b"Stephens", b"Stephenson", b"Stevens", b"Stevenson", b"Stewart"];
const BUCKET_92: vector<vector<u8>> = vector[b"Stokes", b"Stone", b"Stout", b"Strickland", b"Strong", b"Stuart", b"Suarez", b"Sullivan", b"Summers", b"Sutton"];
const BUCKET_93: vector<vector<u8>> = vector[b"Swanson", b"Sweeney", b"Sweet", b"Sykes", b"Talley", b"Tanner", b"Tate", b"Taylor", b"Terrell", b"Terry"];
const BUCKET_94: vector<vector<u8>> = vector[b"Thomas", b"Thompson", b"Thornton", b"Tillman", b"Todd", b"Torres", b"Townsend", b"Tran", b"Travis", b"Trevino"];
const BUCKET_95: vector<vector<u8>> = vector[b"Trujillo", b"Tucker", b"Turner", b"Tyler", b"Tyson", b"Underwood", b"Valdez", b"Valencia", b"Valentine", b"Valenzuela"];
const BUCKET_96: vector<vector<u8>> = vector[b"Vance", b"Vang", b"Vargas", b"Vasquez", b"Vaughan", b"Vaughn", b"Vazquez", b"Vega", b"Velasquez", b"Velazquez"];
const BUCKET_97: vector<vector<u8>> = vector[b"Velez", b"Villarreal", b"Vincent", b"Vinson", b"Wade", b"Wagner", b"Walker", b"Wall", b"Wallace", b"Waller"];
const BUCKET_98: vector<vector<u8>> = vector[b"Walls", b"Walsh", b"Walter", b"Walters", b"Walton", b"Ward", b"Ware", b"Warner", b"Warren", b"Washington"];
const BUCKET_99: vector<vector<u8>> = vector[b"Waters", b"Watkins", b"Watson", b"Watts", b"Weaver", b"Webb", b"Weber", b"Webster", b"Weeks", b"Weiss"];
const BUCKET_100: vector<vector<u8>> = vector[b"Welch", b"Wells", b"West", b"Wheeler", b"Whitaker", b"White", b"Whitehead", b"Whitfield", b"Whitley", b"Whitney"];
const BUCKET_101: vector<vector<u8>> = vector[b"Wiggins", b"Wilcox", b"Wilder", b"Wiley", b"Wilkerson", b"Wilkins", b"Wilkinson", b"William", b"Williams", b"Williamson"];
const BUCKET_102: vector<vector<u8>> = vector[b"Willis", b"Wilson", b"Winters", b"Wise", b"Witt", b"Wolf", b"Wolfe", b"Wong", b"Wood", b"Woodard"];
const BUCKET_103: vector<vector<u8>> = vector[b"Woods", b"Woodward", b"Woodhouse", b"Woodly", b"Wooten", b"Wooton", b"Workman", b"Wright", b"Wyatt", b"Wynn"];
const BUCKET_104: vector<vector<u8>> = vector[b"Wutang", b"Yang", b"Yates", b"Yarrow", b"Yarr", b"Yarbrough", b"York", b"Young", b"Xanders", b"Xanthos"];
const BUCKET_105: vector<vector<u8>> = vector[b"Xenakis", b"Xing", b"Xian", b"Xavier", b"Xue", b"Zamora", b"Zimmerman", b"Pro", b"Autodatter", b"Autoson"];
const BUCKET_106: vector<vector<u8>> = vector[b"Abend", b"Adleman", b"Amdahl", b"Angstrom", b"Ajaxman", b"Apoc", b"Babbage", b"Bacon", b"Baconsmith", b"Band"];
const BUCKET_107: vector<vector<u8>> = vector[b"Bayes", b"Batty", b"Batunas", b"Baxter", b"Berkeley", b"Beers", b"Bezier", b"Black", b"Block", b"Blockchains"];
const BUCKET_108: vector<vector<u8>> = vector[b"Blue", b"Bits", b"Bochs", b"Boon", b"Boomsmith", b"Boomboom", b"Bombom", b"Bogey", b"Bogie", b"Bogieface"];
const BUCKET_109: vector<vector<u8>> = vector[b"Bohr", b"Bolt", b"Boltfetcher", b"Boltmason", b"Bolten", b"Booth", b"Borg", b"Bounce", b"Bourne", b"Bracket"];
const BUCKET_110: vector<vector<u8>> = vector[b"Buff", b"Buffer", b"Bufferson", b"Buffers", b"Cable", b"Cabledatter", b"Cabler", b"Cambridge", b"Carbon", b"Carrier"];
const BUCKET_111: vector<vector<u8>> = vector[b"Carmack", b"Chiller", b"Chenguang", b"Choke", b"Circuit", b"Circuitsmith", b"Circuitmacer", b"Click", b"Clicksmith", b"Clicker"];
const BUCKET_112: vector<vector<u8>> = vector[b"Clickoff", b"Cluster", b"Clusterson", b"Clusterface", b"Cobalt", b"Codd", b"Coil", b"Coilson", b"Coleman", b"Copper"];
const BUCKET_113: vector<vector<u8>> = vector[b"Copperface", b"Core", b"Crosswalks", b"Curie", b"Current", b"Cuifen", b"Cybers", b"Cyberson", b"Cyberface", b"Cyberdatter"];
const BUCKET_114: vector<vector<u8>> = vector[b"Cybermancer", b"Cypher", b"Datas", b"Datason", b"Datamason", b"Datamancer", b"Datasmith", b"Daiquiri", b"Deadmouse", b"Deadman"];
const BUCKET_115: vector<vector<u8>> = vector[b"Deckard", b"Disk", b"Diskdatter", b"Diskson", b"Discsmith", b"Dolby", b"Dongle", b"Dondongle", b"Dongleface", b"Dongleson"];
const BUCKET_116: vector<vector<u8>> = vector[b"Donglefetcher", b"Donglecarrier", b"Donglemancer", b"Drive", b"Driver", b"Dvorak", b"Ellsworth", b"Edison", b"Eight", b"Eleven"];
const BUCKET_117: vector<vector<u8>> = vector[b"Eleventy", b"Erlang", b"Farad", b"Faraday", b"Fiber", b"Fiberson", b"Fiberman", b"Fiberfetcher", b"Fibersmith", b"Fibermason"];
const BUCKET_118: vector<vector<u8>> = vector[b"Fibermancer", b"Five", b"Four", b"Foster", b"Frequenza", b"Futzing", b"Gate", b"Gategate", b"Gates", b"Gater"];
const BUCKET_119: vector<vector<u8>> = vector[b"Gold", b"Goldsmith", b"Granville", b"Gray", b"Green", b"Gilberts", b"Gitson", b"Gitdatter", b"Glitter", b"Harakiri"];
const BUCKET_120: vector<vector<u8>> = vector[b"Hardman", b"Hertz", b"Hopper", b"Hobbs", b"Hobbins", b"Iron", b"Irons", b"Jennings", b"Joule", b"Joulesmith"];
const BUCKET_121: vector<vector<u8>> = vector[b"Jouleson", b"Jouleton", b"Jool", b"Kato", b"Kelvin", b"Kernel", b"Key", b"Kiri", b"Kowasaki", b"Kobayashi"];
const BUCKET_122: vector<vector<u8>> = vector[b"Kilby", b"Kingston", b"Kuwata", b"Ladlad", b"Lamarr", b"Laser", b"Laserface", b"Lasersmith", b"Lasermason", b"Lasermancer"];
const BUCKET_123: vector<vector<u8>> = vector[b"Le", b"Lee", b"Letterhead", b"Li", b"Link", b"Linksen", b"Linkinson", b"Linkmason", b"Legacy", b"Lichtermann"];
const BUCKET_124: vector<vector<u8>> = vector[b"Loader", b"Loadbolt", b"Logic", b"Logicson", b"Login", b"Loop", b"Lovelace", b"Master", b"Macarena", b"McNulty"];
const BUCKET_125: vector<vector<u8>> = vector[b"Mech", b"Mechsmith", b"Mechanick", b"Meier", b"Metal", b"Metall", b"Metalic", b"Metalik", b"Metalmann", b"Metalson"];
const BUCKET_126: vector<vector<u8>> = vector[b"Metalski", b"Mezzanine", b"Minimak", b"Monad", b"Monadi", b"Mosfet", b"Morpheus", b"Morton", b"Molyneux", b"Munge"];
const BUCKET_127: vector<vector<u8>> = vector[b"Munger", b"Munt", b"Munter", b"Mux", b"Nagle", b"Nakamura", b"Nett", b"Nettson", b"Netwall", b"Netzen"];
const BUCKET_128: vector<vector<u8>> = vector[b"Netizen", b"Neo", b"Neon", b"Newton", b"Nine", b"Niven", b"Northbridge", b"Null", b"One", b"Optekar"];
const BUCKET_129: vector<vector<u8>> = vector[b"Onishi", b"Optic", b"Parse", b"Parser", b"Perlman", b"Phillips", b"Phasers", b"Phaserface", b"Phaserson", b"Phaserbekker"];
const BUCKET_130: vector<vector<u8>> = vector[b"Phiser", b"Pieface", b"Pim", b"Pin", b"Pinface", b"Pisano", b"Plug", b"Pocket", b"Port", b"Portal"];
const BUCKET_131: vector<vector<u8>> = vector[b"Portalla", b"Portlet", b"Power", b"Powerbekker", b"Powermason", b"Powell", b"Prime", b"Primetime", b"Process", b"Proto"];
const BUCKET_132: vector<vector<u8>> = vector[b"Protosmith", b"Protoface", b"Proxy", b"Pulse", b"Pulseface", b"Quadrano", b"Quadro", b"Quartz", b"Quanta", b"Quantic"];
const BUCKET_133: vector<vector<u8>> = vector[b"Rambus", b"Rand", b"Render", b"Rendersmith", b"Renderman", b"Resistor", b"Rivest", b"Rhodes", b"Rhineheart", b"Robertson"];
const BUCKET_134: vector<vector<u8>> = vector[b"Rocker", b"Robot", b"Robotson", b"Robotis", b"Robotka", b"Robosmith", b"Robomancer", b"Root", b"Router", b"Routerman"];
const BUCKET_135: vector<vector<u8>> = vector[b"Rowe", b"Rowrow", b"Romero", b"Sadeghpour", b"Salome", b"Sato", b"Sammet", b"Schema", b"Schottky", b"Screw"];
const BUCKET_136: vector<vector<u8>> = vector[b"Screws", b"Screwsmith", b"Scrum", b"Scruescrue", b"Serial", b"Server", b"Seven", b"Shamir", b"Shannon", b"Shocks"];
const BUCKET_137: vector<vector<u8>> = vector[b"Shocksmith", b"Shocksen", b"Shima", b"Shocker", b"Shell", b"Silicon", b"Siliconman", b"Siliconsmith", b"Signal", b"Signalsmith"];
const BUCKET_138: vector<vector<u8>> = vector[b"Signalton", b"Signalface", b"Silver", b"Silverface", b"Silverlock", b"Silverman", b"Silvers", b"Silversmith", b"Sim", b"Sine"];
const BUCKET_139: vector<vector<u8>> = vector[b"Sinewaves", b"Sink", b"Six", b"Sixdigits", b"Slag", b"Smart", b"Socket", b"Socketson", b"Southbridge", b"Song"];
const BUCKET_140: vector<vector<u8>> = vector[b"Sparks", b"Sparkles", b"Sparx", b"Spiz", b"Spizza", b"Spizzo", b"Standard", b"Stanford", b"Stattom", b"Statohm"];
const BUCKET_141: vector<vector<u8>> = vector[b"Statvolt", b"Statwatt", b"Steel", b"Steele", b"Steelman", b"Steelton", b"Steely", b"Stoll", b"Suzuki", b"Swan"];
const BUCKET_142: vector<vector<u8>> = vector[b"Swift", b"Switch", b"Sweeney", b"Takeyama", b"Ten", b"Tesla", b"Teslaface", b"Teslasmith", b"Teslamancer", b"Tesla Warrior"];
const BUCKET_143: vector<vector<u8>> = vector[b"Thermos", b"Three", b"Torrent", b"Torrentface", b"Torrentson", b"Transistor", b"Trimpot", b"Tron", b"Tronton", b"Tronman"];
const BUCKET_144: vector<vector<u8>> = vector[b"Tronek", b"Turing", b"Turingsen", b"Turner", b"Twelve", b"Two", b"Units", b"Volt", b"Voight", b"Watt"];
const BUCKET_145: vector<vector<u8>> = vector[b"Wattface", b"Wattsmith", b"Wave", b"Wescoff", b"Williams", b"Wilson", b"Wire", b"Wiresen", b"Wiresson", b"Wire Warrior"];
const BUCKET_146: vector<vector<u8>> = vector[b"Wireback", b"Wireman", b"Wiresmith", b"Wiremancer", b"Wires", b"Yamamoto", b"Yamaha", b"Zener", b"Zero", b"Zip"];
const BUCKET_147: vector<vector<u8>> = vector[b"Zipface", b"Zipper"];

public(package) fun select(num: u16): String {
    let bucket_idx = num % 146;
    let bucket = match (bucket_idx) {
        0 => BUCKET_0,
        1 => BUCKET_1,
        2 => BUCKET_2,
        3 => BUCKET_3,
        4 => BUCKET_4,
        5 => BUCKET_5,
        6 => BUCKET_6,
        7 => BUCKET_7,
        8 => BUCKET_8,
        9 => BUCKET_9,
        10 => BUCKET_10,
        11 => BUCKET_11,
        12 => BUCKET_12,
        13 => BUCKET_13,
        14 => BUCKET_14,
        15 => BUCKET_15,
        16 => BUCKET_16,
        17 => BUCKET_17,
        18 => BUCKET_18,
        19 => BUCKET_19,
        20 => BUCKET_20,
        21 => BUCKET_21,
        22 => BUCKET_22,
        23 => BUCKET_23,
        24 => BUCKET_24,
        25 => BUCKET_25,
        26 => BUCKET_26,
        27 => BUCKET_27,
        28 => BUCKET_28,
        29 => BUCKET_29,
        30 => BUCKET_30,
        31 => BUCKET_31,
        32 => BUCKET_32,
        33 => BUCKET_33,
        34 => BUCKET_34,
        35 => BUCKET_35,
        36 => BUCKET_36,
        37 => BUCKET_37,
        38 => BUCKET_38,
        39 => BUCKET_39,
        40 => BUCKET_40,
        41 => BUCKET_41,
        42 => BUCKET_42,
        43 => BUCKET_43,
        44 => BUCKET_44,
        45 => BUCKET_45,
        46 => BUCKET_46,
        47 => BUCKET_47,
        48 => BUCKET_48,
        49 => BUCKET_49,
        50 => BUCKET_50,
        51 => BUCKET_51,
        52 => BUCKET_52,
        53 => BUCKET_53,
        54 => BUCKET_54,
        55 => BUCKET_55,
        56 => BUCKET_56,
        57 => BUCKET_57,
        58 => BUCKET_58,
        59 => BUCKET_59,
        60 => BUCKET_60,
        61 => BUCKET_61,
        62 => BUCKET_62,
        63 => BUCKET_63,
        64 => BUCKET_64,
        65 => BUCKET_65,
        66 => BUCKET_66,
        67 => BUCKET_67,
        68 => BUCKET_68,
        69 => BUCKET_69,
        70 => BUCKET_70,
        71 => BUCKET_71,
        72 => BUCKET_72,
        73 => BUCKET_73,
        74 => BUCKET_74,
        75 => BUCKET_75,
        76 => BUCKET_76,
        77 => BUCKET_77,
        78 => BUCKET_78,
        79 => BUCKET_79,
        80 => BUCKET_80,
        81 => BUCKET_81,
        82 => BUCKET_82,
        83 => BUCKET_83,
        84 => BUCKET_84,
        85 => BUCKET_85,
        86 => BUCKET_86,
        87 => BUCKET_87,
        88 => BUCKET_88,
        89 => BUCKET_89,
        90 => BUCKET_90,
        91 => BUCKET_91,
        92 => BUCKET_92,
        93 => BUCKET_93,
        94 => BUCKET_94,
        95 => BUCKET_95,
        96 => BUCKET_96,
        97 => BUCKET_97,
        98 => BUCKET_98,
        99 => BUCKET_99,
        100 => BUCKET_100,
        101 => BUCKET_101,
        102 => BUCKET_102,
        103 => BUCKET_103,
        104 => BUCKET_104,
        105 => BUCKET_105,
        106 => BUCKET_106,
        107 => BUCKET_107,
        108 => BUCKET_108,
        109 => BUCKET_109,
        110 => BUCKET_110,
        111 => BUCKET_111,
        112 => BUCKET_112,
        113 => BUCKET_113,
        114 => BUCKET_114,
        115 => BUCKET_115,
        116 => BUCKET_116,
        117 => BUCKET_117,
        118 => BUCKET_118,
        119 => BUCKET_119,
        120 => BUCKET_120,
        121 => BUCKET_121,
        122 => BUCKET_122,
        123 => BUCKET_123,
        124 => BUCKET_124,
        125 => BUCKET_125,
        126 => BUCKET_126,
        127 => BUCKET_127,
        128 => BUCKET_128,
        129 => BUCKET_129,
        130 => BUCKET_130,
        131 => BUCKET_131,
        132 => BUCKET_132,
        133 => BUCKET_133,
        134 => BUCKET_134,
        135 => BUCKET_135,
        136 => BUCKET_136,
        137 => BUCKET_137,
        138 => BUCKET_138,
        139 => BUCKET_139,
        140 => BUCKET_140,
        141 => BUCKET_141,
        142 => BUCKET_142,
        143 => BUCKET_143,
        144 => BUCKET_144,
        145 => BUCKET_145,
        146 => BUCKET_146,
        147=> BUCKET_147,
        _ => abort
    };

    let index = (num as u64 % bucket.length());
    bucket[index].to_string()
}
