[package]
name = "commander-names"
edition = "2024"
flavor = "vanilla"

[environments]
testnet = "4c78adac"

[dependencies]
suins = { git = "https://github.com/MystenLabs/suins-contracts.git", subdir = "packages/suins", rev = "main" }
