[package]
name = "Commander"
edition = "2024.beta"
license = "MIT"
authors = ["Damir Shamanaev (damirka.ru@gmail.com)"]

[dependencies]
bit-field = { local = "../bit-field" }
codec = { local = "../codec" }
grid = { local = "../grid" }
name-gen = { local = "../name-gen" }

[addresses]
commander = "0x0"
