[package]
name = "Commander"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { override = true, git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "releases/sui-v1.41.0-release" }
Grid = { local = "../grid" }
BitField = { local = "../bit_field" }
NameGenerator = { local = "../name-gen" }
codec = { r.mvr = "potatoes/codec" }

[addresses]
commander = "0x0"

[r.mvr]
network = "testnet"
