[package]
name = "Commander"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
BitField = { local = "../bit_field" }
Codec = { local = "../codec" }
Grid = { local = "../grid" }
NameGenerator = { local = "../name-gen" }

[addresses]
commander = "0x0"
