[package]
name = "Character"
edition = "2024.beta"
authors = ["Sui Potatoes"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }
SVG = { local = "../svg" }
codec = { r.mvr = "potatoes/codec" }

[addresses]
character = "0x0"

[r.mvr]
network = "testnet"
