[package]
name = "Character"
edition = "2024"
authors = ["Sui Potatoes"]

[dependencies]
SVG = { local = "../svg" }
codec = { r.mvr = "potatoes/codec" }

[addresses]
character = "0x0"

[r.mvr]
network = "testnet"
