[package]
name = "Character"
edition = "2024"
authors = ["Damir Shamanaev (damirka.ru@gmail.com)"]
flavor = "vanilla"

[environments]
mainnet = "35834a8a"
testnet = "4c78adac"

[dependencies]
svg = { local = "../svg" }
Codec = { local = "../codec" }
