[package]
name = "Character"
edition = "2024"
authors = ["Damir Shamanaev (damirka.ru@gmail.com)"]

[dependencies]
svg = { local = "../svg" }
Codec = { local = "../codec" }

[addresses]
character = "0x0"
