[package]
name = "Character"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
Sui = { local = "../sui-framework/sui-framework" }
SVG = { local = "../svg" }
Codec = { local = "../codec" }

# For remote import, use the `{ git = "...", subdir = "...", rev = "..." }`.
# Revision can be a branch, a tag, and a commit hash.
# MyRemotePackage = { git = "https://some.remote/host.git", subdir = "remote/path", rev = "main" }

# For local dependencies use `local = path`. Path is relative to the package root
# Local = { local = "../path/to" }

# To resolve a version conflict and force a specific version for dependency
# override use `override = true`
# Override = { local = "../conflicting/version", override = true }

[addresses]
character = "0xfe50fd35667c48ec3342c5182a262aeb8b367188f71524ac8a3ea3e20141e78e"
builder = "0x4574eaf3f1313b584d5004144cd6d6d57d516379d011d6d8e3248c54cfcf90a0"

# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"

# it's alive!
# export PKG=0x2abb8460a38e00a34ad59477526e10996b2106004da443d5f7c81b4caee4f455
# export BUILDER=0x0bbdf7a33564b908f5704f2c0e526aa41b62a66eec557a3b1ef36e1ac3793b9d
# sui client ptb \
# --move-call "$PKG::character::new" \
# "@$BUILDER" "'blazer'" "'bang'" "'181425'" "'d77643'" "'ead4aa'" "'ff0044'" "'733e39'" "'68386c'" \
# --assign x \
# --transfer-objects "[x]" "@$(sui client active-address)" \
# --json
