[package]
name = "commander_names"
edition = "2024"

[dependencies]
suins = { git = "https://github.com/MystenLabs/suins-contracts.git", subdir = "packages/suins", rev = "main" }

[addresses]
commander_names = "0x0"
