name: Test application build

on:
  pull_request:

jobs:
  test_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          cache-dependency-path: './app/package.json'
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm build
