name: Test MVR Packages

on:
    pull_request:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    test-all-mvr-packages:
        name: Use all mvr dependencies in a single package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo install --git https://github.com/Mystenlabs/suiup.git --locked
            - run: suiup install sui -y; suiup install mvr -y
            - working-directory: ./
              run: |
                sui move new test
                cp .github/snippets/test_mvr.move test/sources/test.move
                cd test
                mvr add @potatoes/ascii
                mvr add @potatoes/bit-field
                mvr add @potatoes/codec
                mvr add @potatoes/date
                sui move build
