name: Check Formatting

on:
  pull_request:

jobs:
  prettier_move:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm i @mysten/prettier-plugin-move
      - run: npx prettier-move -c */sources/**/*.move
