name: Walrus (|"|)

on:
  pull_request:

env:
  APP_PATH: app
  DIST_PATH: app/dist
  WALRUS_RELEASE: mainnet-v1.18.2

jobs:
  frontend-app-build:
    name: Install dependencies and upload to walrus sites
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_PATH }}
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Download Sui
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: MystenLabs/sui
          platform: ubuntu
          version: mainnet
          cache: enable
      - name: Create config and environment
        run: |
          yes | sui client;
          sui keytool import ${{ secrets.SITES_PUBLISHER_KEY }} ed25519 --alias publisher;
          sui client new-env --alias mainnet --rpc https://fullnode.mainnet.sui.io:443;
          sui client switch --env mainnet --address publisher;
          sui client balance
      - name: Download walrus
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: MystenLabs/walrus
          platform: ubuntu
          version: ${{ env.WALRUS_RELEASE }}
          cache: enable
      - name: Install walrus sites
        uses: baptiste0928/cargo-install@v3
        with:
          crate: site-builder
          git: https://github.com/MystenLabs/walrus-sites
          branch: mainnet # todo: change this once site builder has releases
          cache-key: ${{ env.WALRUS_RELEASE }} # make it depend on walrus
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          cache-dependency-path: './${{ env.APP_PATH }}/package.json'
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm build
